### ISSUE TITLE
ModuleNotFoundError: No module named 'lsh.cMinhash'

### ISSUE THREAD

**Issue by nithinivi** [mattilyra/LSH#15]
I am using python 3.6.8, after installation when try to import using 
**from lsh import minhash**
I get the following error trace
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nithin/inflict/LSH/lsh/minhash.py", line 9, in <module>
    from .cMinhash import minhash_32, minhash_64
ModuleNotFoundError: No module named 'lsh.cMinhash'

```

**Comment by EggsBenedict** [comment]
did your installation run successfully?

> git clone https://github.com/mattilyra/LSH
> cd LSH
> python setup.py install

took me a few tries to build this and not have it error on building lsh.cMinhash.

**Comment by nithinivi** [comment]
that seems to solve the problem but  why is not working from the pip

**Comment by hgatewood** [comment]
I'm receiving the same ModuleNotFoundError: No module named 'lsh.cMinhash', but I have no error during the installation process. So, I'm not sure why it is not working correctly.

**Comment by zhangxiaohuM** [comment]
> I am using python 3.6.8, after installation when try to import using
> **from lsh import minhash**
> I get the following error trace
> 
> ```
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/nithin/inflict/LSH/lsh/minhash.py", line 9, in <module>
>     from .cMinhash import minhash_32, minhash_64
> ModuleNotFoundError: No module named 'lsh.cMinhash'
> ```

did you solve it

**Comment by nithinivi** [comment]
> > I am using python 3.6.8, after installation when try to import using
> > **from lsh import minhash**
> > I get the following error trace
> > ```
> > Traceback (most recent call last):
> >   File "<stdin>", line 1, in <module>
> >   File "/home/nithin/inflict/LSH/lsh/minhash.py", line 9, in <module>
> >     from .cMinhash import minhash_32, minhash_64
> > ModuleNotFoundError: No module named 'lsh.cMinhash'
> > ```
> 
> did you solve it

Nope  I just managed it with what @EggsBenedict suggested

**Comment by kmaddi-quotient** [comment]
> did your installation run successfully?
> 
> > git clone https://github.com/mattilyra/LSH
> > cd LSH
> > python setup.py install
> 
> took me a few tries to build this and not have it error on building lsh.cMinhash.

Can you suggest the whole procedure of how made it work?
